### ISSUE TITLE
Support Elastic DR

### ISSUE THREAD

**Issue by adv4000** [aws-samples/aws-mgn-launchtemplate-manager#1]
Hi,
MGN and DRS very similar services per design, can you add support for DRS as well?

**Comment by nassy20** [comment]
There is a very similar solution for DRS here: 
https://aws.amazon.com/blogs/storage/managing-aws-elastic-disaster-recovery-launch-templates-at-scale/

that points to this github repo here:
https://github.com/aws-samples/drs-template-manager

Please let me know if it suffice. If not I'd like to learn more about your use case.

**Comment by adv-it** [comment]
@nassy20 exactly what is needed, thanks!
